/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Splash`; params?: Router.UnknownInputParams; } | { pathname: `/Welcome`; params?: Router.UnknownInputParams; } | { pathname: `/audioGenerate`; params?: Router.UnknownInputParams; } | { pathname: `/audioRecord`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/audio/audio` | `/audio/audio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/file/file` | `/file/file`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Splash`; params?: Router.UnknownOutputParams; } | { pathname: `/Welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/audioGenerate`; params?: Router.UnknownOutputParams; } | { pathname: `/audioRecord`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/audio/audio` | `/audio/audio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/file/file` | `/file/file`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Splash${`?${string}` | `#${string}` | ''}` | `/Welcome${`?${string}` | `#${string}` | ''}` | `/audioGenerate${`?${string}` | `#${string}` | ''}` | `/audioRecord${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/audio/audio${`?${string}` | `#${string}` | ''}` | `/audio/audio${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/file/file${`?${string}` | `#${string}` | ''}` | `/file/file${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Splash`; params?: Router.UnknownInputParams; } | { pathname: `/Welcome`; params?: Router.UnknownInputParams; } | { pathname: `/audioGenerate`; params?: Router.UnknownInputParams; } | { pathname: `/audioRecord`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/audio/audio` | `/audio/audio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/file/file` | `/file/file`; params?: Router.UnknownInputParams; };
    }
  }
}
